export const SNOWFLAKE_CLI_RPC_URL = 'SNOWFLAKE_CLI_RPC_URL';
export const SNOWFLAKE_CLI_KEYPAIR_PATH = 'SNOWFLAKE_CLI_KEYPAIR_PATH';
export const SNOWFLAKE_CLI_WALLET_ADDRESS = 'SNOWFLAKE_CLI_WALLET_ADDRESS';
export const SNOWFLAKE_CLI_FEE_ACCOUNT = 'SNOWFLAKE_CLI_FEE_ACCOUNT';
